sudo: required
services: docker
language: bash

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker build -t "blogc/blogc-github-webhook:latest" .

after_success:
  - if [[ "${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}" == "master" ]]; then
    echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin;
    docker push "blogc/blogc-github-webhook:latest";
    fi
